blog_test/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.home, name='blog-home'),
     path('about/', views.about, name='blog-about'),
    path('resume/', views.resume, name='blog-resume'),
    path('blog_post/', views.PostList, name='blog-blg_post'),
    path('blog_detail/<int:pk>', views.PostDetail, name='blog-post_detail'),
]

blog_test/blog_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls')),
]

blog_test/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class AboutPage(models.Model):
    birthday = models.DateField(default=0)
    address = models.TextField(max_length=200)
    number = models.TextField(max_length=20)
    website = models.TextField(max_length=20)
    age = models.PositiveIntegerField(default=0)  # Added a default value for the age field
    email = models.EmailField(max_length=254)
    degree = models.TextField(max_length=254)
    content = models.TextField(max_length=5000000)
    online = models.TextField(max_length=500000)
    my_current_research = models.TextField(max_length=500000)
    my_current_research1 = models.TextField(max_length=500000)
    my_current_research2 = models.TextField(max_length=500000)
    my_current_research3 = models.TextField(max_length=500000)
    my_current_research4 = models.TextField(max_length=500000)
    my_future_goals = models.TextField(max_length=500000)
    my_future_goals1 = models.TextField(max_length=500000)
    my_future_goals2 = models.TextField(max_length=500000)
    my_future_goals3 = models.TextField(max_length=500000)
    my_future_goals4 = models.TextField(max_length=500000)
    my_mission= models.TextField(max_length=500000)
    my_mission1= models.TextField(max_length=500000)
    my_mission2= models.TextField(max_length=500000)
    my_mission3= models.TextField(max_length=500000)
    my_mission4= models.TextField(max_length=500000)
    my_vision= models.TextField(max_length=500000)
    my_vision1= models.TextField(max_length=500000)
    my_vision2= models.TextField(max_length=500000)
    my_vision3= models.TextField(max_length=500000)
    my_vision4= models.TextField(max_length=500000)
    my_quotes= models.TextField(max_length=500000)
    my_quotes1= models.TextField(max_length=500000)
    my_quotes2= models.TextField(max_length=500000)
    my_quotes3= models.TextField(max_length=500000)
    my_quotes4= models.TextField(max_length=500000)

    def __str__(self):
        
        return self.email  


class interests(models.Model):
    interest1 = models.TextField(max_length=500000)
    interest2 = models.TextField(max_length=500000)
    interest3 = models.TextField(max_length=500000)
    interest4 = models.TextField(max_length=500000)
    interest5 = models.TextField(max_length=500000)
    interest6 = models.TextField(max_length=500000)
    interest7 = models.TextField(max_length=500000)
    interest8 = models.TextField(max_length=500000)    

    def __str__(self):
        return self.interest1

class skills(models.Model):
    skill1 = models.TextField(max_length=500000)
    skill2 = models.TextField(max_length=500000)
    skill3 = models.TextField(max_length=500000)
    skill4 = models.TextField(max_length=500000)
    skill5 = models.TextField(max_length=500000)
    skill6 = models.TextField(max_length=500000)
    skill7 = models.TextField(max_length=500000)
    skill8 = models.TextField(max_length=500000)    

    def __str__(self):
        return self.skill1

class workstats(models.Model):
    work1 = models.TextField(max_length=500000)
    work2 = models.TextField(max_length=500000)
    work3 = models.TextField(max_length=500000)
    work4 = models.TextField(max_length=500000)


    def __str__(self):
        return self.work1


class ResumePage1(models.Model):
    Summary = models.TextField(max_length=200)
    aboutme = models.TextField(max_length=500000)
    Address = models.TextField(max_length=500000)
    phone = models.TextField(max_length=500000)
    email = models.TextField(max_length=500000)
    education = models.TextField(max_length=200)
    education_head = models.TextField(max_length=200)
    education_1st_year = models.TextField(max_length=200)
    education_2nd_year = models.TextField(max_length=200)
    education_1st_year_university = models.TextField(max_length=200)
    education_2nd_year_university = models.TextField(max_length=200)
    education_1st_year_briefintro = models.TextField(max_length=500000)
    education_2nd_year_briefintro = models.TextField(max_length=500000)
    experience_head = models.TextField(max_length=200)
    experience_position1 = models.TextField(max_length=200)
    experience_position1_year = models.TextField(max_length=200)
    experience_position2 = models.TextField(max_length=200)
    experience_position2_year = models.TextField(max_length=200)
    experience_position3 = models.TextField(max_length=200)
    experience_position3_year = models.TextField(max_length=200)
    experience_position1_location = models.TextField(max_length=500000)
    experience_position2_location = models.TextField(max_length=500000)
    experience_position3_location = models.TextField(max_length=500000)
    exp1_brief_dscp1= models.TextField(max_length=500000)
    exp1_brief_dscp2= models.TextField(max_length=500000)
    exp1_brief_dscp3= models.TextField(max_length=500000)
    exp2_brief_dscp1= models.TextField(max_length=500000)
    exp2_brief_dscp2= models.TextField(max_length=500000)
    exp2_brief_dscp3= models.TextField(max_length=500000)
    exp3_brief_dscp1= models.TextField(max_length=500000)
    exp3_brief_dscp2= models.TextField(max_length=500000)
    exp3_brief_dscp3= models.TextField(max_length=500000)
    def __str__(self):
        return self.phone

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)
class blg_post(models.Model):
    subject = models.TextField(max_length=200)
    date = models.DateField()
    topic = models.TextField(max_length=500000)
    reference_to = models.TextField(max_length=200)
    create_by = models.TextField(max_length=200)
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.create_by

blog_test/blog/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse
from django.views import generic
'''from .models import skills,AboutPage,workstats,interests,ResumePage1,blg_post'''
from .models import *

def home(request):
    return render(request, 'blog/home.html')


'''def about(request):
    post = AboutPage.objects.all()
    return render(request, 'blog/about.html', {'post': post} )'''

def about(request):
    post = AboutPage.objects.all()
    work = workstats.objects.all()
    skill = skills.objects.all()
    interest = interests.objects.all()
    return render(request,'blog/about.html',{'post': post ,'work': work,'skill':skill,'interest':interest})




def resume(request):
    ResumePage = ResumePage1.objects.all()
    return render(request, 'blog/resume.html',{'ResumePage': ResumePage })


def PostList(request):
    '''queryset = blg_post.objects.filter(status=1).order_by('-created_on')'''
    queryset = blg_post.objects.all()
    return render(request, 'blog/blg_posts.html',{'blg_post': queryset })


def PostDetail(request, pk):
    queryset = get_object_or_404(blg_post, pk=pk)
    return render(request, 'blog/post_detail.html',{'blg_post': queryset })

'''class PostList(generic.ListView):
    queryset = blg_post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/blg_posts.html'

class PostDetail(generic.DetailView):
    model = blg_post
    template_name = 'blog/post_detail.html'  '''
 

blog_test/blog/templates/blog/about._backup_30th_June_2023.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}Emil Varghese Blog{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
{% load static %}

  <link rel="icon" href="{% static 'assets/img/favicon.png' %}">

  <link rel='apple-touch-icon' href="{% static 'assets/img/apple-touch-icon.png' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <!-- Vendor CSS Files -->
    <link rel='stylesheet'  href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'  %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'  %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/remixicon/remixicon.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}">

  <!-- Template Main CSS File -->
  <link rel='stylesheet' href="{% static 'assets/css/style.css' %}">

  <!-- =======================================================
  * Template Name: Personal
  * Updated: Jun 18 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
{%block content %}
{% for post in post %}

<body>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

      <h1><a href="index.html">Emil Varghese</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a> -->
      <h2>I'm a passionate <span>Phd Scholar and Environmental Data Analyst </span> from India</h2>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link active" href="#header">Home</a></li>
          <li><a class="nav-link" href="#about">About</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <div class="social-links">
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div>

    </div>
  </header><!-- End Header -->

  <!-- ======= About Section ======= -->
  <section id="about" class="about">

    <!-- ======= About Me ======= -->
    <div class="about-me container">

      <div class="section-title">
        <!--<h2>About</h2>
        <p>Learn more about me</p>-->
      </div>

      <div class="row">
        <div class="col-lg-4" data-aos="fade-right">
          <img src="{% static 'assets/img/emil.png' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
          <h3>Doctral Researcher Fellow</h3>
          <p class="fst-italic">
          {{ post.online }}
          </p>
          <div class="row">
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>{{ post.birthday }}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>{{ post.website }}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>{{ post.number }}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>{{ post.address }}</span></li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>{{ post.age }}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>{{ post.degree }}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>{{ post.email }}</span></li>
              </ul>
            </div>
          </div>
          <p>
          {{ post.content }}
          </p>
        </div>
      </div>

    </div><!-- End About Me -->
     {% endfor %}


    <!-- ======= Counts ======= -->
    <div class="counts container">
      <div class="row">
        {% for work in work %}
        <div class="col-lg-3 col-md-6">
          <div class="count-box">
            <i class="bi bi-emoji-smile"></i>
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
            <p>{{ work.work1 }}</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
          <div class="count-box">
            <i class="bi bi-journal-richtext"></i>
            <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
            <p>{{ work.work2 }}</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="bi bi-headset"></i>
            <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
            <p>{{ work.work3 }}</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
          <div class="count-box">
            <i class="bi bi-award"></i>
            <span data-purecounter-start="0" data-purecounter-end="24" data-purecounter-duration="1" class="purecounter"></span>
            <p>{{ work.work4 }}</p>
          </div>
        </div>

      </div>
        {% endfor %}
    </div><!-- End Counts -->

    <!-- ======= Skills  ======= -->
    {% for skill in skill %}
    <div class="skills container">

      <div class="section-title">
        <h2>Skills</h2>
      </div>

      <div class="row skills-content">

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">{{ skill.skill1 }} <i class="val">100%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">{{ skill.skill2 }} <i class="val">90%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">{{ skill.skill3 }} <i class="val">75%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">{{ skill.skill4 }} <i class="val">80%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">{{ skill.skill5 }} <i class="val">90%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">{{ skill.skill6 }}<i class="val">55%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

      </div>

    </div><!-- End Skills -->
     {% endfor %}
    <!-- ======= Interests ======= -->
    <div class="interests container">
      {% for interest in interest %}
      <div class="section-title">
        <h2> Interests </h2>>
      </div>

      <div class="row">
        <div class="col-lg-3 col-md-4">
          <div class="icon-box">
            <i class="ri-store-line" style="color: #ffbb2c;"></i>
            <h3>{{ interest.interest1 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
          <div class="icon-box">
            <i class="ri-bar-chart-box-line" style="color: #5578ff;"></i>
            <h3>{{ interest.interest2 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
          <div class="icon-box">
            <i class="ri-calendar-todo-line" style="color: #e80368;"></i>
            <h3>{{ interest.interest4 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">
          <div class="icon-box">
            <i class="ri-paint-brush-line" style="color: #e361ff;"></i>
            <h3>{{ interest.interest5 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-database-2-line" style="color: #47aeff;"></i>
            <h3>{{ interest.interest6 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-gradienter-line" style="color: #ffa76e;"></i>
            <h3>{{ interest.interest7 }}</h3>
          </div>
        </div>
        <div class="col-lg-3 col-md-4 mt-4">
          <div class="icon-box">
            <i class="ri-file-list-3-line" style="color: #11dbcf;"></i>
            <h3>{{ interest.interest8 }}</h3>
          </div>
        </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div><!-- End Interests -->

  <div class="credits">
    <!-- All the links in the footer should remain intact. -->
    <!-- You can delete the links only if you purchased the pro version. -->
    <!-- Licensing information: https://bootstrapmade.com/license/ -->
    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
    Designed by <a href="https://bootstrapmade.com/">Emilcorp</a>
  </div>

  <!-- Vendor JS Files -->
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
 

 {% endblock content %}
</body>

</html>

blog_test/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}Emil Varghese Blog{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
{% load static %}

  <link rel="icon" href="{% static 'assets/img/favicon.png' %}">

  <link rel='apple-touch-icon' href="{% static 'assets/img/apple-touch-icon.png' %}">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


    <link rel='stylesheet'  href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'  %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'  %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/remixicon/remixicon.css' %}">
  <link rel='stylesheet'  href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}">

  <!-- Template Main CSS File -->
  <link rel='stylesheet' href="{% static 'assets/css/style.css' %}">

  <!-- =======================================================
  * Template Name: Personal
  * Updated: Jun 18 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

      <h1><a href="index.html">Emil Varghese</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a> -->
      <h2>I'm a passionate <span>Phd Scholar and Environmental Data Analyst </span> from India</h2>



      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link active" href="#header">Home</a></li>
          <li><a class="nav-link" href="{% url 'blog:blog-about' %}">About</a></li>
          <li><a class="nav-link" href="{% url 'blog:blog-resume' %}">Resume</a></li>
          <li><a class="nav-link" href="{% url 'blog:blog-blg_post' %}">Blog</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->





      <div class="social-links">
        <a href="https://instagram.com/emi.varghese" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="https://www.linkedin.com/in/emilvarghese916/" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div>

    </div>
  </header><!-- End Header -->

 
  <div class="credits">
    <!-- All the links in the footer should remain intact. -->
    <!-- You can delete the links only if you purchased the pro version. -->
    <!-- Licensing information: https://bootstrapmade.com/license/ -->
    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
    Designed by <a href="https://bootstrapmade.com/">EmilCorp</a>
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

blog_test/blog/templates/blog/blg_posts.html
{% extends "blog/base_blg_posts.html" %}
      
 {% block content %}
<style>
    
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>

    <header class="masthead" >
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                  <div class="site-heading">
                   <!-- <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>-->
                        <div class="container">
                    <div class="section-title">
         <br><br>
        <h2>Welcome to my Emil's Research Blog</h2>
        <p>I just Love what I Do</p>
      </div>

                </div>
                    </div>
                  </div>
                </div>
            </div>
              </header>
            
            <br> <br>
            <div class="container">
                <div class="row">
                <br> <br>
              <!-- Blog Entries Column -->
              <div class="col-md-8 mt-3 left">
                    {% for post in blg_post %}
                <div class="card mb-4" >
                  <div class="card-body">
                    <h2 class="card-title">{{ post.subject }}</h2>
                    <p class="card-text text-muted h6">{{ post.create_by }} | {{ post.date}} </p>

                    <p class="card-text">{{post.topic|slice:":200" }}</p>
                    <a href="{% url 'blog:blog-post_detail' pk=post.pk %}" class="btn btn-primary">Read More &rarr;</a>

                  </div>
                 
                </div>
                {% endfor %}
            </div>
                {% block sidebar %}
                <br> <br>
                {% include 'blog/sidebar.html' %}
                {% endblock sidebar %}
                <br> <br>
            </div>
        </div>
        <br> <br>
{%endblock%}

blog_test/blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}

{%endblock content%}

blog_test/blog/templates/blog/post.html
{% extends "blog/base.html" %}

{% block content %}

{%endblock content%}

blog_test/blog/templates/blog/post_detail.html
{% extends 'blog/base_blg_posts.html' %} {% block content %}

<br><br> 
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">

        <h1>{% block title %} {{ blg_post.subject }} {% endblock title %}</h1>
        <p class=" text-muted">{{ blg_post.create_by }} | {{ blg_post.date }}</p>
        <p class="card-text ">{{ blg_post.topic | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
  </div>
</center>
</div>

{% endblock content %}

blog_test/blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
  <!-- <div class="col-md-4 float-right ">
<div class="card my-4">
     <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text">This is on multiple article and blog on my research in Aerosol Atmoshpere </p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>-->

{% endblock sidebar %}